name: タグとリリースの自動生成
on:
  pull_request:
    branches:
      - main
    types: [closed]
jobs:
  create_release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/')
    steps:
      - name: ソースコードのcheckour
        uses: actions/checkout@v3
      - name: ブランチ名からバージョンの取得
        run: |
          RELEASE_VERSION=`echo ${{ github.event.pull_request.head.ref }} | sed 's/release\///'`
          echo "RELEASE_VERSION=${RELEASE_VERSION}" >> $GITHUB_ENV
      - name: タグの作成
        run: |
          git tag $RELEASE_VERSION
          git push origin $RELEASE_VERSION
      - name: リリースノートの取得
        run: |
          RELEASE_TITLE=$(ls -1 release/ | grep "$RELEASE_VERSION" | head -n 1)
          RELEASE_BODY=$(cat "release/${RELEASE_TITLE}")
          echo "RELEASE_TITLE=${RELEASE_TITLE}" >> $GITHUB_ENV
          echo "RELEASE_BODY<<EOF" >> $GITHUB_ENV
          echo "${RELEASE_BODY}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: リリースの作成
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          release_name: ${{ env.RELEASE_TITLE }}
          body: ${{ env.RELEASE_BODY }}
          draft: false
          prerelease: false